import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { SummaryTable } from "../components/Tables/SummaryTable";
import { DateTitle } from "../components/UI/DateTitle";
import { Typography } from "@mui/material";

import { BASE_URL } from "../api/constants";

import { StarknetDay } from "../types";

const Home: NextPage = () => {

  const [date, setDate] = React.useState<string>();
  const [starknetDay, setStarknetDay] = React.useState<StarknetDay>();
  
  React.useEffect(() => {

    const _date = new Date(Date.now());
    setDate(`${_date.getFullYear()}-${_date.getMonth() + 1}-${_date.getDate()}`);

    // const _date = "2022-05-19";
    // setDate(_date);
    const URL = `${BASE_URL}/${_date}`;

    const getAndSetStarknetDay = async function(url: string) {
      const _res = await fetch(URL);
      const res = await _res.json();

      setStarknetDay(res.data.starknetDay);
    }

    getAndSetStarknetDay(URL);    
  }, []);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Spy Accounts</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <DateTitle date={date} />
      <SummaryTable organizedAccountsActivity={starknetDay?.organizedAccountsActivity || {}} />
    </div>
  )
}

export default Home;
