import React from "react";
import type { NextPage } from "next";
import Head from "next/head";

import CircularProgress from '@mui/material/CircularProgress';
import { Box } from "@mui/material"

import { AccountTable } from "../components/Tables/AccountTable/AccountTable";
import { DateTitle } from "../components/UI/DateTitle";
import { Container, Typography } from "@mui/material";
import { MyAppBar } from "../components/UI/MyAppBar";
import { formaTimestampToDateForData, formatTimestamp } from "../utils";

import { BASE_URL } from "../api/constants";

import { BigNumber } from "ethers";
import { StarknetDay } from "../types";
import { 
  ContractDataFromBDD, 
  AccountState,
  CallsSummary
} from "../types";
import { FunctionCall } from "starknet-analyzer/src/types/organizedStarknet";
import { forceCast } from "../utils/index";
import { TypographyColor } from "../utils/constants";

const Home: NextPage = () => {
  
  return (
    <React.Fragment>
      <Head>
        <title>Spy Accounts</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <MyAppBar isMainPage />
      <Container>
        <Typography>Hello, welcome on the starknet analyzer website :)</Typography>
      </Container>
    </React.Fragment>
  );
}

export default Home;
